name: dentist_dashboard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.63.0
  data_table_2: ^2.5.7
  get: ^4.6.5
  flutter_switch: ^0.3.2
  universal_html: ^2.2.3
  flutter_login: ^4.2.1
  flutter_svg: ^2.0.7
  go_router: ^10.1.2
  http: ^1.1.0
  path: ^1.8.3
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: arabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
    - family: english
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
